### ISSUE TITLE
Error 521 Web Server down

### ISSUE THREAD

**Issue by TonyPwny** [libretro-thumbnails/libretro-thumbnails#104]
I am experiencing an Error 521 Web Server down when trying to retrieve/view images.  I can no longer download images via the Retroarch content downloader nor web browser.

**Comment by RobLoach** [comment]
Looks like a CloudFlare block. It's possible your IP was flagged or something. Not sure there's anything we can do on our end, you could use a VPN to get around it. It is also possible to download all the thumbnails through git:
https://github.com/libretro-thumbnails/libretro-thumbnails#libretro-thumbnails

The [GitHub Desktop](https://desktop.github.com/) will also do it too, if you want a UI around it.

**Comment by i30817** [comment]
https://thumbnails.libretro.com/ is up, the subdirectories are not.

**Comment by TonyPwny** [comment]
I do not think this is an IP block situation.  Using different internet connections, the issue still persists.

**Comment by RobLoach** [comment]
SHould be good now.
