### ISSUE TITLE
Resident Evil - Director's Cut (USA) for Playstation 1 has wrong box art.

### ISSUE THREAD

**Issue by Lyle-Tafoya** [libretro-thumbnails/libretro-thumbnails#105]
There are 2 different versions of Resident Evil Director's Cut on the Playstation. There is the normal version and the dual-shock version. However, the dual-shock version box art is currently being used for both.

I believe this is the correct image: https://www.retroplace.com/pics/ps/packshots/x52506--resident-evil-directors-cut.png.pagespeed.ic.gqeEksiC4f.webp

**Comment by masanasake** [comment]
@Lyle-Tafoya this was corrected in https://github.com/libretro-thumbnails/Sony_-_PlayStation/pull/228 Would you mind closing this issue?
