### ISSUE TITLE
Changes to master not being pulled by "Download Thumbnails" option when selecting games

### ISSUE THREAD

**Issue by masanasake** [libretro-thumbnails/libretro-thumbnails#108]
I have made several requests recently, and they were carried out/added to the master branch. These thumbnail additions only get pulled by using the "desktop menu", which is not supported in the steam version. Is there a way to check where the per game "download thumbnails" option is pulling these from since it doesn't appear to be from master? Thank you.

**Comment by MarcoEstevez** [comment]
@RobLoach any ideas, seems like some actions are needed for updates being applied on RA, and Desktop app points directly to the repo, but don't know the details behind

**Comment by masanasake** [comment]
I've tried a few this morning and it looks like the issue is fixed. I also went through and made my annoying "issues" into "pull requests" for varying PS and Nintendo systems. Could someone please review/approve them?

**Comment by RobLoach** [comment]
The thumbnails server was manually updated and rebooted.
