### ISSUE TITLE
Missing entries

### ISSUE THREAD

**Issue by masanasake** [libretro-thumbnails/libretro-thumbnails#110]
Is it possible to set up a file/database for missing box art/snaps/titles for each system like you did for my last Wii request that would be available to the public to keep track of what still needs to be added?

**Comment by MarcoEstevez** [comment]
it does already exists :-P check this out

https://github.com/RobLoach/libretro-thumbnails-check

**Comment by masanasake** [comment]
Ah, I had no idea. Foolish me. Thanks!
