### ISSUE TITLE
Create Commodore CD32 thumbnails repo

### ISSUE THREAD

**Issue by ner00** [libretro-thumbnails/libretro-thumbnails#117]
I have created a repo for this platform and added a few dozen thumbnails to begin with, check [that repo](https://github.com/ner00/Commodore_-_CD32).

**Comment by RobLoach** [comment]
We'll need a corresponding database for this from https://github.com/libretro/libretro-database ... Know if it's named something different in redump?

**Comment by ner00** [comment]
I see.  In redump's database they call it:
`<name>Commodore - Amiga CD32</name>`

**Comment by RobLoach** [comment]
:heavy_check_mark:
