### ISSUE TITLE
http://thumbnails.libretro.com/

### ISSUE THREAD

**Issue by alfrix** [libretro-thumbnails/libretro-thumbnails#12]
Seems to be using http://github.com/libretro/libretro-thumbnails

Shouldn't be this repo?

**Comment by RobLoach** [comment]
I believe CloudFlare is just caching it...
http://thumbnails.libretro.com/?AvoidTheCache

**Comment by RobLoach** [comment]
This should be okay, CloudFlare is just slow sometimes. There should be another cronjob for it happening on Wednesday.
