### ISSUE TITLE
Lexaloffle Games - Pico-8

### ISSUE THREAD

**Issue by BlackSheepBoy69** [libretro-thumbnails/libretro-thumbnails#120]
Hello, I'd like a "named snap" section for Pico-8. I can provide some if you'd be interested.

**Comment by BlackSheepBoy69** [comment]
Here are 18, I've run them through GIMP so they can have minimal file size

https://www.mediafire.com/file/w4b10017mgznmqx/PICO8SCREENSHOTS.rar/file

**Comment by BlackSheepBoy69** [comment]
Closing - not interested anymore. Just going to use a zoomed in stretched picture from the actual covers for Pico-8

**Comment by RobLoach** [comment]
This would be for the retro8 core? Not sure it's published on buildbot, yet.... Would need to have an associated database for it though.

**Comment by BlackSheepBoy69** [comment]
All I know is RetroFlow is using this repository for downloaded snaps and they said to ask if you'd open a thing for it. This is not necessarily related to RetroArch, just RetroFlow and regarding adding Pico-8 to RetroFlow.
