### ISSUE TITLE
New repo for Vircon32 thumbnails

### ISSUE THREAD

**Issue by vircon32** [libretro-thumbnails/libretro-thumbnails#131]
Hello, I am currently integrating a a new console in RetroArch: Vircon32. Its core info and games database were already added to their repos. Game thumbnails are also ready but it seems like that would first require a new repo to be created here. Can you please create a thumbnails repo for Vircon32?

Meanwhile I have uploaded the content to one of my repos [(link here)](https://github.com/vircon32/vircon32-libretro-thumbnails) so that you can access it. As required, all images are PNG and have been kept to 512 px width maximum.

Thank you in advance.

**Comment by gouchi** [comment]
@RobLoach If possible to create dedicated repository.

Thank you.

**Comment by RobLoach** [comment]
Thanks so much! This looks great. 
https://github.com/libretro-thumbnails/vircon32

**Comment by vircon32** [comment]
Thank you RobLoach! I have accepted the invitation, so when new Vircon32 games are made I will try to add the corresponding images. I am closing this issue now, but feel free to reopen it if needed :)
