### ISSUE TITLE
Resolution guidelines/standards

### ISSUE THREAD

**Issue by gerad-not-edgar** [libretro-thumbnails/libretro-thumbnails#132]
The current guidelines state:

"Images with native width larger than 512px should be scaled down to 512px wide
Images with native width of 512px or less should be added as-is"

It looks to me like Retroarch displays a maximum size of 512x512, otherwise it scales it to be that. For a lot of japanese nintendo box arts, the vertical length is longer; would it be best to try and standardize/ reword the guidelines to 512 being the longest dimension regardless of orientation, vs gbc for example is 512x646 (when it should probably be 406x512)? Would save space and possibly effort. Seems like a lot of the japanese boxart is underdeveloped by comparison, so it would be nice to set a standard if all this is true. I'm not planning on going through and resizing anything, just seems like that 512 width has been prevalent. Seems like a lot of the japanese boxart is underdeveloped by comparison, so it would be nice to set a standard going forward if all this is true.

**Comment by gerad-not-edgar** [comment]
So after some testing, Retroarch definitely displays more pixels vertically, but I'm not sure exactly what the max dimensions are. There's definitely scaling that takes place when it exceeds the vertical limit. Maybe it's just my setup, but I didn't notice a discernable difference between the image displayed through Retroarch using images at 283x512 and 512x879. Can anyone confirm or deny this?

**Comment by RobLoach** [comment]
There isn't really a maximum height. 512px wide, keeping the original aspect ratio.

**Comment by gerad-not-edgar** [comment]
I guess the question moreso is if there's truly any benefit to resizing. For instance, a lot of the n64 box art I have a pull for has been resized to 512 width due to the assumption it would be deemed "less quality" when the current ones no doubt are, but only when viewed in github vs how they are actually represented in retroarch. So I've got quite a few I didn't include for this reason: more accurate color and clean since some of the current are shots of physical boxes, but they're lower resolution because of the size.

**Comment by RobLoach** [comment]
It's 512px because, depending on the video driver, RetroArch creates Textures for the thumbs at 512px. Also don't want to take up too much file space :wink: 

Feel free to push up any improvements that you think would be better. Lots of the color grading can be subjective, but the team can review and fix up where neeeded. Thanks!
