### ISSUE TITLE
Incorrectly-named thumbnails: PC Engine / TurboGrafx-16 CD-ROM: Akumajou Dracula X - Chi no Rondo (Japan)

### ISSUE THREAD

**Issue by c0d3h4x0r** [libretro-thumbnails/libretro-thumbnails#143]
As you can see [here](https://git.libretro.com/libretro-assets/libretro-database/-/blob/master/metadat/redump/NEC%20-%20PC%20Engine%20CD%20-%20TurboGrafx-CD.dat#L79), the libretro dB uses the name `Akumajou Dracula X - Chi no Rondo (Japan)`.

However, as you can see [here](https://github.com/libretro-thumbnails/NEC_-_PC_Engine_CD_-_TurboGrafx-CD/tree/eb6915372bb841a1dfc8b46f7063e322f3f72a5b/Named_Boxarts), the thumbnails use two different names (`Akumajou Dracula X - Chi no Rondo (Japan) (Konami)` or `Akumajou Dracula X - Chi no Rondo (Japan) (FABT, FACT)`), neither of which matches the dB entry.

As such, RetroArch (latest release or nightly build) fails to find and download thumbnails for this game, even when the correct CHD or CUE/BIN game files are present (both on disk and in the RetroArch playlist) and have checksums matching the dB entry.

This mismatch/breakage between the libretro dB and the libretro thumbnails is one example of a somewhat common problem. Would it be possible to periodically bulk-auto-update all libretro thumbnail filenames to match changes coming from the libretro dB, to keep them in sync?

**Comment by RobLoach** [comment]
Would be great to do so. There have been some attempts to have a script to rename them. Would love some help in something like that.

**Comment by c0d3h4x0r** [comment]
Is the `@hashvalue` part of each thumbnail folder's name intended to indicate the corresponding dB file's git commit number?
