### ISSUE TITLE
Remove common metadata from filenames

### ISSUE THREAD

**Issue by RobLoach** [libretro-thumbnails/libretro-thumbnails#16]
Remove some common strings from names to avoid having to have duplicates. We'd have to update RetroArch to remove those strings from the detected name.

- ` [b]`
- ` (Proto)`
- ` (Rev 1)`
- ` (Rev 2)`
- ` (Rev 3)`
- ` (Rev 4)`
- ` (Rev 5)`
- ` (Rev 6)`

We'd need to update it in RetroArch before removing the entries from the filenames, and removing the duplicates.

**Comment by kwyxz** [comment]
Good call. On my system I usually end up creating hard links but afaik GitHub does not support this.

**Comment by alfrix** [comment]
(Proto 1-2)
(set 1-23)   <the biggest Buena Suerte (Spanish_Portuguese, set 23)

there are some case where set is with other info:
(set 1, new encryption)
(set 1, 315-5177)
(US set 1)

**Comment by markwkidd** [comment]
I'm concerned about this approach. To give a real world example, recently there has been a thread in the forums about Conky's Bad Fur Day. Apparently only version 1.0 of the SNES ROM found in the No-Intro ROM collection works -- version 1.1 does not. This information is relevant, and sometimes vital to the user experience.

Information such as the Revision number help users not have to randomly try each version in the collection till they find the one with the correct MAME decryption support for their scenario.

Then again I haven't seen any posts in the forums about this.

Twinaphex has said in the past that he would be willing to add support for an updated playlist format as long as there was backwards compatibility with the current format. Something as simple as a new playlist format including with a path to the corresponding thumbnail would be a much more graceful solution from what I can tell.

**Comment by markwkidd** [comment]
In other words: if this metadata is being removed from the playlists and thumbnail filenames, and it's important in some situations, where else is the metadata available to users?

**Comment by RobLoach** [comment]
Removing the need of the metadata in the thumbnail filename. The playlist title would stay the same.

**Comment by alfrix** [comment]
@RobLoach made a branch to test 
https://github.com/libretro-thumbnails/Nintendo_-_Nintendo_Entertainment_System/tree/Clean-metadata

**Comment by alfrix** [comment]
Made one, needs some tweaking i'll fix it later
```
Get-ChildItem -path "G:\Emuladores\RetroArch\thumbnails\Nintendo - Nintendo Entertainment System" -Recurse -Directory |
ForEach-Object {
	$folder=$_.fullname ;
	
	if ("$folder" -Like "*Named*") {
		Get-ChildItem $folder -file | 
		foreach {
			switch -regex ($_) {
			#TODO: preserve the biggest file
			#FIXME: if multiple things are found this would have to run more than once
				".+ \(Rev (A|B|C|D|E|1|2|3|4|5)\)*" {echo $_.Name; Move-Item -Force -LiteralPath $_.FullName ($_.FullName -replace ' \(Rev.+\)','' )}
				".+ \(Proto\)*" {echo $_.Name; Move-Item -Force -LiteralPath $_.FullName ($_.FullName -replace ' \(Proto\)','' )}
				".+ \[b\]*" {echo $_.Name;  Move-Item -Force -LiteralPath $_.FullName ($_.FullName -replace ' \[b\]','' )}
			}
		}
	}	
}
pause
```

**Comment by alfrix** [comment]
Current branch status was achieved with 
```
function replace-rename-file
{
	param([string]$current_file, [string]$new_file)

	if (Test-Path $new_file){ 
		If ((Get-Item $current_file).length -gt (Get-Item $new_file).length){ #Preserve the highest quality
			Write-host $_.FullName;
			Write-host $newname ;
			Move-Item -Force -LiteralPath $current_file $new_file;
		}else{
			Remove-Item -LiteralPath $current_file}
	}else{
		Move-Item -Force -LiteralPath $current_file $new_file
	}
}

for ($i=0; $i -lt 3; $i++){ 
Get-ChildItem -path "G:\Emuladores\RetroArch\thumbnails\Nintendo - Nintendo Entertainment System" -Recurse -Directory |
ForEach-Object {
	$folder=$_.fullname ;
	
	if ("$folder" -Like "*Named*") {
		Get-ChildItem $folder -file | 
		foreach {
			switch -regex ($_) {
				".+ \(Rev.+\)*" {
					$newname=($_.FullName -replace ' \(Rev.+\)','' );
					replace-rename-file $_.FullName $newname;
					break;
				}
				".+ \(Prot.+\)*" {
					$newname=($_.FullName -replace ' \(Prot.+\)','' );
					replace-rename-file $_.FullName $newname;
					break;
				}
				".+ \[b\]*" {
					$newname=($_.FullName -replace ' \[b\]','' );
					replace-rename-file $_.FullName $newname;
					break;
				}
			}
		}
	}	
}
}
pause
```
Notice that i'm replacing all the (rev*) and (prot*) with regex

**Comment by markwkidd** [comment]
Still on my tangent, I've created a thread in the Development forum about an enhanced playlist format that would allow this to be addressed in what I feel would be a more elegant and functional way: https://forums.libretro.com/t/proposal-for-playlist-file-format-v2/14667

**Comment by alfrix** [comment]
@markwkidd kind of like the idea of a better playlist, i will share my thoughts on the thread.  But in this particular case adding a thumbnail name or location to every playlist entry, would need someone to maintain some kind of database with aliases. and even if that is implemented the repo still needs deduping.

**Comment by RobLoach** [comment]
You can now toggle the brackets in the name in playlist view.
