### ISSUE TITLE
Add "Amstrad - CPC" section?

### ISSUE THREAD

**Issue by maxlefou** [libretro-thumbnails/libretro-thumbnails#17]
I mean, Retroarch supports it enough well to get them, right?

**Comment by RobLoach** [comment]
We don't have a database for this. Know where one exists?

**Comment by maxlefou** [comment]
I know a french one, [here](http://www.cpc-power.com/index.php?page=database). But that one is not only about games, it's about any softwares for it. So it has, like 15k entries :o

**Comment by RobLoach** [comment]
Added from TOSEC.
