### ISSUE TITLE
Would like to post the full set as a torrent

### ISSUE THREAD

**Issue by xizdaqrian** [libretro-thumbnails/libretro-thumbnails#21]
Hi,

I'd like to post this huge beast as a torrent. It might make for easier retrieval than waiting in the client.

Are there any issues from you, regarding this? I will, of course, give you attribution in the description and a README file in the torrent. I'll include a link to this repo. If you like, I can post a link to the torrent here, or email it to you, so you can put it in the MarkDown file for the repo.

Regards,
Rodney Fisk

**Comment by RobLoach** [comment]
Seems like a great idea! The thumbnails are frequently updated, so we'll have to figure out an update path moving forwards.

**Comment by xizdaqrian** [comment]
TYVM

Regards,
~Rodney

**Comment by markwkidd** [comment]
archive.org has a pretty simple but clever system.

To translate it to our terms:
1. the MAME thumbnail repo is updated
2. a buildbot-like script automatically deletes the old `MAME-libretro-thumbnails-2018-11-27.torrent` and creates a new ``MAME-libretro-thumbnails-2018-12-04.torrent`
3. The torrent has its "web seed" set to the current thumbnail packs URL

The way this works for archive.org is that the web seeds are always there making sure the torrent is complete, but also individual connected users contribute bandwidth.

It doesn't seem **that** difficult to script.

**Comment by RobLoach** [comment]
https://datproject.org is another option.
