### ISSUE TITLE
Migrate to Git LFS

### ISSUE THREAD

**Issue by alfrix** [libretro-thumbnails/libretro-thumbnails#23]
After working quite a bit on this set of repos, it has come to my attention the inherent flaw of git when it's used to track binary files, every time a binary it's changed all the history remain in every member local set, it's extremely wasteful in terms of space, since it will pull every version of the file, and store it on the .git folder on a giant pack file that can grow to several GB pretty fast, just look at the following screenshot of my local copy, see the big blocks, especially MAMEs ~8GBs.

![space](https://user-images.githubusercontent.com/1247237/37153380-53d6a00e-22bb-11e8-83db-2aec95e9bc1d.jpg)

Enter Git LFS, the solution to our problem, with the LFS system the history will only track pointers to the file and the LFS subsystem will download the last version when you checkout, nothing really changes to the normal use of Git, it's transparent, supported by Github and easily/included available on most platforms.

More info:
1. [Quck explanatory video](https://www.youtube.com/watch?v=9gaTargV5BY)
2. [One of the devs at linuxcon](https://youtu.be/p3Pse1UkEhI?t=232)

[Configuring Git LFS](https://help.github.com/articles/configuring-git-large-file-storage/)

PLAN:

In our case what we want to track the PNGs

```
git lfs track "*.png"
```

we should commit and distribute the new .gitattributes created

```
git add .gitattributes
git commit -m "Use Git LFS to track PNGs"
```

As seen in the [tutorial](https://github.com/git-lfs/git-lfs/wiki/Tutorial) this is't not enough we should remove the files and re-add

```
git rm --cached *.png
git add *.png
git commit -m "Convert last commit to LFS"
```

Since we created a repo without LFS before, and put hundreds of MB in there, after all these steps, the old version still has all the large files in git, not in LFS. 

the tutorial leads to use git lfs migrate, there is a discussion on how to rewrite history [here](https://github.com/github/git-lfs/issues/326)

```
git lfs migrate import --include="*.png" --include-ref=refs/heads/master
```

and finally 

```
git push -f
```

Cleaning up the .git directory after migrating, it's not required to do this, but it would take days before the history expires

```
git reflog expire --expire-unreachable=now --all
git gc --prune=now
```
if lfs migrate doesn't work, we may have to nuke the history

@RobLoach this seems the correct path forward for libretro-thumbnails
@twinaphex this could also be beneficial on libretro/retroarch-assets since @alcaro had to flatten the repo for this very reason.

Tagging @kivutar @kwyxz to keep them on the loop.

**Comment by RobLoach** [comment]
Seems like a great idea... The files are stored on their server? Could we just flatten the repo every once in a while?

When cloning, you can use the following to just download the latest...
```
git clone --depth=1 REPOURL
```

**Comment by alfrix** [comment]
>The files are stored on their server?
exactly the same as of now, but the underlying sync is what changes.

>Could we just flatten the repo every once in a while?
switching to lfs would eliminate the need to do that. 

>When cloning, you can use the following to just download the latest...
usually you clone once then pull, this is where it gets messy for binary blobs

**Comment by kwyxz** [comment]
This seems indeed like a wonderful idea. If I understand correctly, once the migration is done and the LFS is set there's no change for contributors (in terms of commits / merges) and it's pretty transparent, right?

By the way, is RetroArch's online downloader using the new repo now? Last time I checked it was still using the old one (but I haven't checked out recently).

**Comment by RobLoach** [comment]
> Is RetroArch's online downloader using the new repo now?

Yes, http://thumbnailpacks.libretro.com

**Comment by alfrix** [comment]
>once the migration is done and the LFS is set there's no change for contributors (in terms of commits / merges) and it's pretty transparent, right?

no changes to the workflow at all, it should not affect anything except that you will regain disk space, and the repo history will not bloat, ``` git lfs prune``` will retain only the lastest files

I have been doing some tests, and the caveat seems that since the conversion push it's a forced push (rewrites history) devs need to do: ```git reset origin/master --hard``` at least in the case of individual repositories, i don't know how the super-repo will behave

**Comment by alfrix** [comment]
i should clarify that ```git reset origin/master --hard``` it's only needed once to change the local repo to the new system, or you could just re-clone after the conversion it's done

**Comment by alfrix** [comment]
Converted https://github.com/libretro-thumbnails/Watara_-_Supervision to lfs
if you cloned libretro-thumbnails just do:
```git submodule update --recursive --remote --init```
it should pull it without any problems

**Comment by alfrix** [comment]
Unfortunately LFS has a quota, i reverted back the changes.

If anyone save some space, go to the desired submodule and do:
```
git pull --depth 1 && git gc --prune=all
```
