### ISSUE TITLE
Images smaller than 1KB do not load

### ISSUE THREAD

**Issue by alfrix** [libretro-thumbnails/libretro-thumbnails#36]
It seems like this is an old bug, but i can still reproduce it
https://forums.libretro.com/t/boxart-images-smaller-than-900-bytes-dont-appear
@RobLoach Can you confirm this please
We surely made it worse by using imgbot, i think the best course of action is uninstalling the bot
i'll be fixing the offending repos in the weekend, mostly 2600, spectrum and the like

**Comment by alfrix** [comment]
Fixed 2600 - 5200 - MSX - MSX2 - ZX 81 - ZX Spectrum

**Comment by RobLoach** [comment]
Is this still an issue? Is it a problem with the ImgBot’s compression?

**Comment by RobLoach** [comment]
Just uninstalled it.... Should we revert the ImgBot commits?

**Comment by alfrix** [comment]
> Is this still an issue? 

Yes,
> Is it a problem with the ImgBot’s compression?

No, it's a weird bug of XMB

> Should we revert the ImgBot commits?

No, a lot of initial commits have images that are affected, we need to decompress the affected images to make them bigger (i have calculated a near a hundred megabytes of increase in total, not too much)
i have started doing it but got really bored even with automated tools, it's still time consuming, maybe tomorrow i'll finish fixing it.
Ideally we should fix XMB, but i have no idea what could be the cause of this, the code is really messy at this point.

**Comment by alfrix** [comment]
There are no more images smaller than 1 KB in any repo (at least for now)
