### ISSUE TITLE
Consider updating submodules that are outdated in comparison libretro/libretro-thumbnails

### ISSUE THREAD

**Issue by ElTipejoLoco** [libretro-thumbnails/libretro-thumbnails#4]
Near as I can tell, the following submodules have had significant changes or updates made to them in the original repo that were not inherited by this current target. While updating the files twinaphex improved seems like a no-brainer and I'll gladly get on that after submitting this, I'm not clear on whether or not the GBC submodule will actually benefit from the renaming or not and would prefer to hear some input on the matter before attempting to 'update' it:
- [x] Update Nintendo - Game Boy Color repository with renamed files and DAT ([09/27 PR](https://github.com/libretro/libretro-thumbnails/commit/5d9d67a82188fe01d1a068911c1982e66196c78c) merged on original repo)
- [x] Update Sony - PlayStation/Named_Boxarts/Dead or Alive (USA).png ([09/30](https://github.com/libretro/libretro-thumbnails/commit/e47d8365067183601ff5e4d324b96c37d50464d7))
- [x] Update Sony - PlayStation/Named_Boxarts/WipEout 3 (USA).png ([09/30](https://github.com/libretro/libretro-thumbnails/commit/563dc8ffbad2e363c9d2b9e329aaa8063c3bc650))
- [x] Update Sony - PlayStation/Named_Boxarts/Wipeout XL (USA).png ([09/30](https://github.com/libretro/libretro-thumbnails/commit/fa8439df752e47ccad5d82fc1f2accbc96e501b5))

**Comment by RobLoach** [comment]
I believe those changes were brought into the submodules. Both the PlayStation changes, and gb renames. Mind confirming?

Looking to update the main repo with the latest changes?

**Comment by ElTipejoLoco** [comment]
Can confirm. My Git shell must've gotten confused from the main hub not linking to every submodule's master branch. False alarm.

**Comment by RobLoach** [comment]
The submodules themselves could be updated to the latest. Don't think we can update them in the GitHub GUI.
