### ISSUE TITLE
poor quality MAME screens and titles

### ISSUE THREAD

**Issue by markwkidd** [libretro-thumbnails/libretro-thumbnails#40]
@metchebe and @RobLoach my understanding is that there are upscaled MAME thumbnails mixed into the MAME thumbnail repository.

I didn't see an issue started about that anywhere github -- if indeed there is no issue, then maybe this can be where we talk about that.

Is the problem specifically that thumbnails which are natively less than 512px wide have been scaled up to 512px wide? Are there any other issues or would looking at the 512px images reveal all of the problematic images.

**Comment by metchebe** [comment]
I have not checked to see if there are guidelines for these things, but here is what I have noticed.

For Named_Snaps and Named_Titles:
- Most thumbnail 'packs' except MAME have native 1:1 pixel perfect screenshots, saved as 8bpp images whenever possible (i.e. max 256 colors). They have no further processing (like aspect ratio correction, for example).
- For MAME, however, _all images_ I have seen have been scaled to 512px (wide I believe). This, in my opinion, not only looks bad but also inflates the file sizes.

For Named_Boxarts:
- Some boxarts (flyers in this case) smaller than 512px have been upscaled to 512px. This, in my opinion, is also unnecesary for the same reason as above.
- For my personal use, I've downscaled the large original flyers from @markwkidd 's repository to 512px on the _long side_ (not necessarily width, in fact in most cases in height). I have kept small flyers at their original size. This is a personal preference, it makes the UI snappier, but others may prefer higher resolution versions.

**Comment by markwkidd** [comment]
All snaps and titles are 512px??  💥 😑 

I thought I helped create this thumbnail collection but dang that sounds all wrong. Maybe I should disavow my work on the repo.

**Comment by markwkidd** [comment]
@metchebe as I understand it the resolution policy is:
  * Images smaller than 256px wide are at original resolution
  * Images between 256px and 512px are downscaled to 256px
  * Images greater than 512px are downscaled to 512px

**Comment by metchebe** [comment]
@markwkidd I'm sorry, I had not seen the latest update to [http://thumbnails.libretro.com/MAME/](http://thumbnails.libretro.com/MAME/)

I see now that some screenshots have been fixed, but some remain scaled to 512px.

**Comment by markwkidd** [comment]
I worked on this so long ago I don't really remember.

Are there any that have been scaled improperly to other dimensions, like 256px etc?

**Comment by metchebe** [comment]
On Linux, you can check with the `file` command which ones are `color RGB`. It also shows the image dimensions.

This would mostly show which ones have been scaled and have over 256 colors (for interpolation), although checking still would be necessary since some  games do have higher color depth screenshots (Street Fighter III for example).

**Comment by markwkidd** [comment]
I'm Windows 10 only right now, although I do have a msys2 environment with bash and all that fun stuff. Let me see if I can also figure out how to sort based on color depth.

**Comment by metchebe** [comment]
[Cygwin](https://www.cygwin.com/) works too.

**Comment by alfrix** [comment]
i have worked a lot on the boxarts/flyers to fix the bad quality, but only reached the letter E, they are very custom at this point, please do not paste a generic pack of flyers over them.

**Comment by markwkidd** [comment]
I apologize, because if the problem is this widespread it must be my mistake in scripting the image sizes when this repository was first created. I can't understand how so many could be wrong otherwise.

For my purposes, I'm now doing something I should have done back then: I'm creating individual thumbnail repos for mame2000, mame2003, mame2003-plus and maybe the other ones. For example: https://github.com/markwkidd/mame2000-thumbnail-sources

My repos will only have original/native resolution. You will be free to draw on them to make improvements to this repo if you like.

**Comment by markwkidd** [comment]
For what its worth, I have now finished three native-resolution thumbnail repositories:
  * https://github.com/markwkidd/mame2003-plus-thumbnail-sources
  * https://github.com/markwkidd/mame2003-thumbnail-sources
  * https://github.com/markwkidd/mame2000-thumbnail-sources

I say "finished" in the sense that they all have a complete set of native resolution "snap" and "title" screenshots -- the "Named_Boxarts" folders are not complete. These were created mostly by scripts querying arcadeitalia but there was also a few hours of manual correction and addition on my part.

Please fee free to use these, and if it would be helpful for me to come up with a similar thumbnail repository for MAME 2010, 2014, etc let me know. It takes a few hours but it's not a terribly intensive process with my tools.

**Comment by alfrix** [comment]
Great work! 1:1 snaps/titles could reduce repo size and improve quality, i'll port them over with additional optipng optimization (i think i said it a million times, but again: optipng does not reduce quality)

at a glance they seem alright, @metchebe can you confirm?

dividing the repo into multiple versions will make it much more difficult to maintain, let's see how much it reduces after the snaps and titles are 1:1 and decide from there

**Comment by alfrix** [comment]
i ported them, the repo size got a reduction of 1.7gb so far and they look much better too,
still there are around 10k snaps and titles missing which are from >2003 cores

**Comment by markwkidd** [comment]
Nice! I would be glad to prepare thumbnail packs for MAME 2010 and 2014
which I think I can take on in the month of January I haven't dealt much
with 2016 but I may also try to put something together for that too unless
there's a another approach.

**Comment by alfrix** [comment]
that would be really appreciated, i estimate no more than 500mb in total if all the snaps and titles are replaced, that would mean another gigabyte of reduction.
i would keep the mechanical (pinballs, slot machines) out of this repo, they got added in 2014, i don't think anyone uses that RA
the only big part that would remain after that is the flyers, but i don't see a way to reduce that other than removing any mechanical flyers that would remain

**Comment by markwkidd** [comment]
I have also recently done updates to the scanner databases for these
earlier cores to trim "no dumps" and other known non-working sets.

I will plan to make that part of the process for 2010 and 2014 when I work
on thumbnails, once I update my scripts for the to add filtering for Device
and Mechanical which the early ones don't have.

At that point I should be able to identify any Mechanical thumbnails which
are still in this metarepository by shell script and produce a list.

**Comment by markwkidd** [comment]
Hello @alfrix ! I have produced a MAME 2010 native resolution thumbnail repository which you can find here: https://github.com/markwkidd/mame2010-thumbnail-sources

There are a handful of romsets for which I could not compile Snap and Title thumbnails and I couldn't get them running in MAME 2010 either. However it looks like the majority of these are early examples of mechnical games in MAME so that may not be a problem anyway in light of your previous comment. Here is the list: https://github.com/markwkidd/mame2010-thumbnail-sources/issues/1

When I have the next opportunity I will work on a MAME 2014 thumbnail repo.

**Comment by markwkidd** [comment]
@alfrix I must apologize that for MAME 2003 and MAME 2010 I left some thumbnails out by mistake -- games that have a "NODUMP" or "BADDUMP" flag in MAME, but still work anyway. I have fixed this in my scripts and found the missing images.

The missing thumbnails were added to my "sources" in this MAME 2003 commit: https://github.com/markwkidd/mame2003-thumbnail-sources/commit/596e5467e0047ace87fc8fee0289e31fbae9dbf3

Here is the corresponding MAME 2010 missing thumbnail commit: https://github.com/markwkidd/mame2010-thumbnail-sources/commit/2d7dd1397137370687f21533dd8adc6ea87478cc

I hope that this does not come as a major annoyance to your system for managing the files.

**Comment by markwkidd** [comment]
@alfrix I have the next one for you -- MAME 2015 thumbnails. (MAME 2014 is in the process of being renamed to MAME 2015 since it is based on MAME 0.160 from March 2015)

https://github.com/markwkidd/mame2015-thumbnail-sources/

Thank you!

**Comment by markwkidd** [comment]
@alfrix I not think there has been a MAME 2016 thumbnail collection before now. So this is not so much an update as a new submission.

MAME 2016 thumbnails: https://github.com/markwkidd/mame2016-thumbnail-sources

**Comment by markwkidd** [comment]
@alfrix I really appreciate your willingness to work with me on these submissions after I just showed up one day! I'm going to close this issue because I don't have anything else to offer that will fix my previous work or improve on what other folks have contributed.

In the future however as we add new games to MAME 2003-Plus I will probably open an issue here to coordinate with you on the thumbnails. There are already about 30-40 new games I need to add thumbnails for since my last update but I may wait till it's a few more before I go through that.

**Comment by alfrix** [comment]
@markwkidd thank you very much for your contributions, the repo is now at an excellent shape, only current mame is missing, i'll probably do it later, that and changing xmb code to load from this repo for all the mame playlists (desktop ui already does it)

**Comment by alfrix** [comment]
i forgot, if you need to add stuff just send a pr (512px max wide and etc)
if you remember please run `optipng -o7 -strip=all *.png` to the images that you will pr 
(put the new images in a separate folder to optimize only the new ones and then place them back)
again thank you very much for your help
