### ISSUE TITLE
submiting a mising boxart 

### ISSUE THREAD

**Issue by medievil1** [libretro-thumbnails/libretro-thumbnails#43]
wasn't sure the proper procedure, this is a missing original Playstation  boxart for Running Wild (USA)
<img width="256" alt="running wild usa" src="https://user-images.githubusercontent.com/38597905/51445079-f1f95200-1cce-11e9-99b1-706250411d42.png">

[Running Wild [USA].zip](https://github.com/libretro-thumbnails/libretro-thumbnails/files/2777035/Running.Wild.USA.zip)

**Comment by medievil1** [comment]
found another Pitfall 3D - Beyond the Jungle (USA)
<img width="256" alt="pitfall 3d - beyond the jungle usa" src="https://user-images.githubusercontent.com/38597905/51445251-0f2f2000-1cd1-11e9-931c-54c3f8206f64.png">
[Pitfall 3D - Beyond the Jungle (USA).zip](https://github.com/libretro-thumbnails/libretro-thumbnails/files/2777045/Pitfall.3D.-.Beyond.the.Jungle.USA.zip)

**Comment by alfrix** [comment]
Hi, thanks

For future reference the correct repository is https://github.com/libretro-thumbnails/Sony_-_PlayStation

Fork it, 
![captura](https://user-images.githubusercontent.com/1247237/51450676-5983c180-1d10-11e9-84e6-b301ffa6257a.JPG)


select upload files and your files (you may want to create the folders)
The names must match the [database](https://raw.githubusercontent.com/libretro/libretro-database/master/dat/Sony%20-%20PlayStation.dat)
you can double check in RA by going to the Main Menu > Information > Database Manager
![captura](https://user-images.githubusercontent.com/1247237/51450636-35c07b80-1d10-11e9-9117-2d3e9b51c1e6.JPG)

once you are satisfied do a pull request
![captura](https://user-images.githubusercontent.com/1247237/51450734-9fd92080-1d10-11e9-8862-235b85b49aa5.JPG)
