### ISSUE TITLE
Contribute thumbnails for Thomson MO/TO computers

### ISSUE THREAD

**Issue by Zlika** [libretro-thumbnails/libretro-thumbnails#44]
Hi!
I would like to contribute thumbnails for games of the Thomson MO/TO computers (emulated by the Theodore core). How can I proceed? As you use one repository for each system I cannot just send a PR.
Regards

**Comment by RobLoach** [comment]
I've set up a repo for you! It should propagate to the thumbnail server shortly...

https://github.com/libretro-thumbnails/Thomson_-_MOTO

Thanks a lot for going through this :smile:

**Comment by Zlika** [comment]
Thanks!
Do you have any advice on the image resolutions I should use?
I've read the REAME.md file on this, but I also saw that their is a pending PR on this point with no clear consensus.
I have a script that automatically downloads the boxarts/snaps/titles images from the screenscraper.fr website. On this site, the boxarts images generally have a high resolution, so I plan to resize them to a 512px width because I saw it was a common resolution used by other thumbnails repositories. For the snaps/titles, the images have generally a resolution of 320x200px, so I don't know if I have to resize them down to 256px width (a resolution I saw on some other thumbnails repositories) or if I have to keep their native resolution.

**Comment by RobLoach** [comment]
Width: 512px

Less than that, just leave as is.

**Comment by RobLoach** [comment]
Done! GREAT JORB!
