### ISSUE TITLE
Some packs are truncated

### ISSUE THREAD

**Issue by berarma** [libretro-thumbnails/libretro-thumbnails#47]
Hi.

I've tried downloading the following packs from Retroarch and from a browser:
http://thumbnailpacks.libretro.com/MAME.zip
http://thumbnailpacks.libretro.com/Nintendo%20-%20Super%20Nintendo%20Entertainment%20System.zip

The downloaded size is smaller than the size displayed in the page and the file can't be unzipped. It doesn't seem to be a network problem. The size reported when the download starts matches the downloaded size.

**Comment by realnc** [comment]
I can confirm. I tried to download the SNES pack from within RA (Linux version) and it doesn't work. The zip is not getting extracted. I downloaded manually and it seems the ZIP file is corrupt:

```
$ wget 'http://thumbnailpacks.libretro.com/Nintendo%20-%20Super%20Nintendo%20Entertainment%20System.zip'
--2019-07-13 14:37:17--  http://thumbnailpacks.libretro.com/Nintendo%20-%20Super%20Nintendo%20Entertainment%20System.zip
Resolving thumbnailpacks.libretro.com... 2606:4700:30::681c:1553, 2606:4700:30::681c:1453, 104.28.20.83, ...
Connecting to thumbnailpacks.libretro.com|2606:4700:30::681c:1553|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 184966021 (176M) [application/zip]
Saving to: 'Nintendo - Super Nintendo Entertainment System.zip'

$ unzip Nintendo\ -\ Super\ Nintendo\ Entertainment\ System.zip 
Archive:  Nintendo - Super Nintendo Entertainment System.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of Nintendo - Super Nintendo Entertainment System.zip or
        Nintendo - Super Nintendo Entertainment System.zip.zip, and cannot find Nintendo - Super Nintendo Entertainment System.zip.ZIP, period.
```

**Comment by RobLoach** [comment]
I'll try rebuilding them manually.

**Comment by RobLoach** [comment]
This should be fixed now... Make sure filenames are ASCII.

**Comment by gitTerebi** [comment]
Still an issue, please check.

**Comment by RobLoach** [comment]
Magnavox - Odyssey2/Named_Boxarts/Type & Tell (USA).png
Nintendo - Nintendo DS/Named_Boxarts/Race Driver - Create & Race (Europe) (En,Fr,De,Es,It).png
Nintendo - Nintendo DS/Named_Boxarts/Race Driver - Create & Race (USA) (En,Fr,De,Es,It).png
SNK - Neo Geo CD/Named_Boxarts/Top Hunter - Roddy & Cathy (Japan).png
Sony - PlayStation 2/Named_Boxarts/Beyond Good & Evil (USA) (En,Fr,Es).png
Sony - PlayStation 2/Named_Boxarts/Unison - Rebels of Rhythm & Dance (USA).png
Sony - PlayStation 2/Named_Boxarts/Starsky & Hutch (USA).png
Sony - PlayStation 2/Named_Boxarts/Metal Slug 4 & 5 (USA) (Disc 1) (Metal Slug 4).png
Sony - PlayStation 2/Named_Boxarts/DreamWorks & Aardman Flushed Away (USA).png
```
Sony - PlayStation 2/Named_Boxarts/Adventures of Cookie & Cream, The (USA).png
Sony - PlayStation 2/Named_Boxarts/Ratchet & Clank - Size Matters (USA).png
Sony - PlayStation 2/Named_Boxarts/Ape Escape - Pumped & Primed (USA).png
Sony - PlayStation 2/Named_Boxarts/Black & Bruised (USA).png
Sony - PlayStation 2/Named_Boxarts/Ratchet & Clank - Going Commando (USA).png
Sony - PlayStation 2/Named_Boxarts/Simpsons, The - Hit & Run (USA).png
Sony - PlayStation 2/Named_Boxarts/Ratchet & Clank - Up Your Arsenal (USA) (En,Fr,Es).png
Sony - PlayStation 2/Named_Boxarts/Ratchet & Clank (USA) (En,Fr,De,Es,It).png
Sony - PlayStation 2/Named_Boxarts/Wallace & Gromit in Project Zoo (USA).png
Sony - PlayStation 2/Named_Boxarts/Wallace & Gromit - The Curse of the Were-Rabbit (USA).png
Sony - PlayStation 2/Named_Boxarts/Asterix & Obelix - Kick Buttix (USA).png
Sony - PlayStation 2/Named_Boxarts/Soul Nomad & the World Eaters (USA).png
Sony - PlayStation 4/Named_Boxarts/Final Fantasy X & X-2 HD Remaster (Europe).png
The 3DO Company - 3DO/Named_Boxarts/Advanced Dungeons & Dragons - Slayer (USA).png
The 3DO Company - 3DO/Named_Boxarts/Advanced Dungeons & Dragons - Deathkeep (USA).png
```

**Comment by RobLoach** [comment]
Any other packs that you see breaking?
