### ISSUE TITLE
[Switch] Thumbnails not showing up on patched N64 games.

### ISSUE THREAD

**Issue by iGom** [libretro-thumbnails/libretro-thumbnails#49]
Thumbnails are not showing up on patched N64 games, because they not follow names from database/playlist. 
In database patched roms have (Rev 1, 2 etc.) at the end of the name, while thumbnails from Libretro have (Rev A, B etc.) so RetroArch doesn't download them or doesn't show after manual download.

**Comment by RobLoach** [comment]
Would love some help getting them  up to date! Feel free to use the GitHub UI, or the desktop client to rename them as needed and issue pull requests.

**Comment by iGom** [comment]
Cool, I'll start doing this over the weekend

**Comment by ner00** [comment]
@RobLoach If I wanted to contribute an entry for a patched game, how would I go about it? For example: an SNES game which was only released in Japanese, there is a reputable translation patch. If I apply said patch, test the ROM, how would I then create an entry and consequent pull request?

I'll give a very specific example, which already exists: `Ys V - Kefin, Lost Kingdom of Sand (Japan) [T-En by Aeon Genesis v1.00] [n]`

I can see that it exists inside this database: https://github.com/libretro/libretro-database/blob/master/metadat/libretro-dats/Nintendo%20-%20Super%20Nintendo%20Entertainment%20System.dat

Should I just add it there and push?
How about the naming scheme, which are the guidelines? ie: `Tales of Phantasia (Japan) [T-En by DeJap v1.2] [Add by Spinner 8 and friends v1.0]`

**Comment by RobLoach** [comment]
You'll find a few popular hacks/translations over in the `hacks` folder....
https://github.com/libretro/libretro-database/blob/master/metadat/hacks/Nintendo%20-%20Super%20Nintendo%20Entertainment%20System.dat

**Comment by ner00** [comment]
Thanks for pointing that out, but it doesn't really answer my questions in relation to the specific exmple that I gave. There are quite a few recognized patched roms, like the example I mentioned before, and my question was if there was the possibility to add others that might not be on the list. It would be nice to have a pre-patched rom being recognized and having art being pulled out of the box; obviously I'm not suggesting to include every variation of every pre-patched rom though.
