### ISSUE TITLE
Travis Script to check for improper names

### ISSUE THREAD

**Issue by RobLoach** [libretro-thumbnails/libretro-thumbnails#51]

**Comment by anewuser** [comment]
Can you use it to check the width too?

https://unix.stackexchange.com/a/235957
https://github.com/travis-ci/travis-ci/issues/78

**Comment by RobLoach** [comment]
That'd be cool!

**Comment by Exia-Ti885** [comment]
how to use the script, please let me know, thank youu

**Comment by RobLoach** [comment]
https://github.com/libretro-thumbnails/libretro-thumbnails#testing

**Comment by Exia-Ti885** [comment]
Yes, I did read that, but its dont tell how to use it, I try to type the script on cmd but not work, sorry for my bad english
