### ISSUE TITLE
Suggestion: split thumbnail packs

### ISSUE THREAD

**Issue by anewuser** [libretro-thumbnails/libretro-thumbnails#55]
Even though I only wanted snapshots, I had to download full packs from http://thumbnailpacks.libretro.com/ .

You could save everyone's bandwidth and time by splitting each pack into `Named_Snaps.zip`, `Named_Titles.zip` etc.

**Comment by RobLoach** [comment]
Using the Playlist Thumbnails Updater may be an option to get around this.
![Screenshot at 2019-08-22 01-51-59](https://user-images.githubusercontent.com/25086/63489210-80110300-c47f-11e9-8ee9-3d10fb779597.png)

**Comment by anewuser** [comment]
I don't actually use RetroArch or Libretro, but that's a useful scraping option. Maybe you can add a notice about it at the top of the packs index page.

**Comment by ner00** [comment]
This creates an overcomplication with no benefit, the opposite in fact; it would require constant maintenance and packaging of said folders. As if that wasn't reason enough, it just does not help one inch Libretro/RetroArch users, which is the entire point. 

For example, I wanted to download just the snapshots, I literally searched for this `github download subfolder`. The first result is a StackOverflow question about this generic issue with several answers, among them is one which mentions: 

> There are four options summarized below. And for those that prefer a more hands-on explanation, I've put together a YouTube video: [Download Individual Files and Folders from GitHub](https://www.youtube.com/watch?v=1HRvE_Oa_aM).

One of the easier ways among the third-party tools is [DownGit](https://github.com/MinhasKamal/DownGit)

**Comment by RobLoach** [comment]
Going to close this issue. The thumbnail packs are legacy in RetroArch. Feel free to download the zips directly from github if you want the full thing without using git, or using downgit, or git, or whatever tool you find the easiest.

![TYzwW](https://user-images.githubusercontent.com/25086/73312509-dc2e3f00-41f6-11ea-8adb-5b46ff75059d.png)
