### ISSUE TITLE
Refined Boxarts

### ISSUE THREAD

**Issue by RobLoach** [libretro-thumbnails/libretro-thumbnails#56]
https://www.reddit.com/r/emulation/comments/cyhn50

**Comment by MarcoEstevez** [comment]
Ummm...

Quite interesant, I'll have a look

**Comment by kwyxz** [comment]
That looks pretty great. We might want to ask the original poster if he allows us to use these.

**Comment by kwyxz** [comment]
They allowed us, we'll be checking out what is worth using https://www.reddit.com/r/emulation/comments/hw0nvd/nes_classic_accurate_usa_cover_art_250_covers_wip/fz4ovju/

**Comment by kwyxz** [comment]
Follow-up in #80
