### ISSUE TITLE
Sharp - X68000

### ISSUE THREAD

**Issue by anewuser** [libretro-thumbnails/libretro-thumbnails#58]
The Sharp X68000 is [supported by Libretro](https://docs.libretro.com/library/px68k/), but has no thumbnails repository.

**Comment by RobLoach** [comment]
Great! Added Gradius in https://github.com/libretro-thumbnails/Sharp_-_X68000 .

**Comment by RobLoach** [comment]
Feel free to add some of the thumbs there :wink:
