### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by RobLoach** [libretro-thumbnails/libretro-thumbnails#6]
Is there a license we could stick on this? Unsure how that would work.

**Comment by kwyxz** [comment]
Sounds complicated, since we don't own the rights to the original arts.

**Comment by guoyunhe** [comment]
I was also wondering how to package this into Linux repository if it doesn't indicate a license...

**Comment by RobLoach** [comment]
May be best to avoid packaging the thumbnails until a clear license is figured out. The Playlist Thumbnail Downloader is likely the best tool for the job right now.

**Comment by kwyxz** [comment]
Screenshots are fair game, but there's no way we'd be able to clear every copyright on box arts and flyers. We're in a dark grey area.

**Comment by guoyunhe** [comment]
I also think we should not package it. It is 8GB huge. No users want to download them all... Download thumbnail on demand is the best solution.
