### ISSUE TITLE
Thumbnails for Pokémon Ruby and Sapphire do not download

### ISSUE THREAD

**Issue by sarahlicity** [libretro-thumbnails/libretro-thumbnails#63]
When doing a metadata download within RetroArch, the thumbnails for Pokemon Ruby and Sapphire (Rev 1, specifically) do not properly download. I believe this may be due to the fact that in the libretro-database repository, the country tag is different to that in this repository.

**Comment by Melon-Bread** [comment]
You are absolutely correct. I submitted a pull request to fix the issue. Good catch!

**Comment by ner00** [comment]
@RobLoach So... maybe close this issue now? :)

**Comment by RobLoach** [comment]
:rocket:
