### ISSUE TITLE
Nintendo Gameboy color - List of incorrectly named files

### ISSUE THREAD

**Issue by sammy2142** [libretro-thumbnails/libretro-thumbnails#67]
Some incorrectly named files:
Legend of Zelda, The - Link's Awakening DX (USA, Europe) (Rev B) (SGB Enhanced) (GB Compatible).png
Should be
Legend of Zelda, The - Link's Awakening DX (USA, Europe) (Rev 2) (SGB Enhanced) (GB Compatible).png

(there are many files like this in the GBC collection that are using (Rev A) etc when retroarch uses (Rev 1))

Legend of Zelda, The - Oracle of Ages (USA).png
Should be
Legend of Zelda, The - Oracle of Ages (USA, Australia).png

and

Legend of Zelda, The - Oracle of Seasons (USA).png
Should be
Legend of Zelda, The - Oracle of Seasons (USA, Australia).png

I would of created a pull but the online editor doesn't appear to let you rename image files only code files :(

**Comment by MarcoEstevez** [comment]
Yes, there are some inconsistencies and mismatches between file names and database entries, we are aware of it, I will try to fix orphans on this repo.

**Comment by MarcoEstevez** [comment]
This pr should address it

https://github.com/libretro-thumbnails/Nintendo_-_Game_Boy_Color/pull/13

**Comment by sammy2142** [comment]
Awesome thanks :)
