### ISSUE TITLE
Optimize PNGs

### ISSUE THREAD

**Issue by alfrix** [libretro-thumbnails/libretro-thumbnails#7]
I was going to download the entire tree and do it myself, but wouldn't be better to have a bot doing it?

https://github.com/apps/ImgBot

ImgBot uses ImageMagick to optimize images through the LosslessCompress() routine from the The .NET wrapper Magick.NET. This means that while the file size is going down, the quality and dimensions remain intact.

It will create Pull requests, that have to be aproved.

**Comment by RobLoach** [comment]
Great idea! Let's try it out on Atari Lynx as a test case.

**Comment by alfrix** [comment]
have you added it yet?

i have added it to my repo, but i don't how long is supposed to take.

it can be configured if necessary:
```
.imgbotconfig
{
    "schedule": "daily" // daily|weekly|monthly
    "ignoredFiles": [
        "*.jpg",                   // ignore by extension
        "image1.png",              // ignore by filename
        "public/special_images/*", // ignore by folderpath
    ]
}
```

**Comment by RobLoach** [comment]
Installed the application on the GitHub repo. Didn't add the config.

**Comment by alfrix** [comment]
It's optional, basically if the bot makes too many PRs it can be limited.

**Comment by alfrix** [comment]
I had lost hope and started doing it myself, but seems that the bot has done it's job and very well i may add, examine the results and if happy add the bot to the rest of the repos.

**Comment by RobLoach** [comment]
Saw you go through a lot of the optimisations! Nice one. The ImgBot PR looks pretty good. The image seems to render in RetroArch well....

![aaa](https://user-images.githubusercontent.com/25086/33850662-947c8254-de82-11e7-827e-ac51c37d32ff.png)

Shall we enable it for ALL the repos now? :+1:

**Comment by alfrix** [comment]
I say yes, we can examine the PRs before merge, an even if something turns out wrong we can revert the commit.

**Comment by RobLoach** [comment]
Enabled, and a bunch are coming in already! :+1:

**Comment by kwyxz** [comment]
FWIW I usually run pngquant on boxarts before I push them. Are we sure the bot is not going to make size bigger in those cases?

**Comment by RobLoach** [comment]
Don't think it uploads larger sizes.

**Comment by kwyxz** [comment]
Perfect then!

**Comment by dabutvin** [comment]
👍 happy to help

That's right - ImgBot will not add a file to be committed if the result of `LosslessCompress()` routine is false

https://github.com/dabutvin/ImgBot/blob/master/ImgBot.Function/CompressImages.cs#L108
https://github.com/dlemstra/Magick.NET/blob/master/Source/Magick.NET/Shared/Optimizers/IImageOptimizer.cs#L74

**Comment by RobLoach** [comment]
That's awesome! I love this thing. We have it running across all repositories now, and it has been working really well. Thanks a lot!
