### ISSUE TITLE
SNES: Rock 'n Roll Racing thumbs don't work because of typo

### ISSUE THREAD

**Issue by mrmatteastwood** [libretro-thumbnails/libretro-thumbnails#70]
Hi, team! The game "Rock 'n Roll Racing" is spelled in various ways in the Nintendo SNES database:

![rnrracing](https://user-images.githubusercontent.com/22120259/74245353-288f7980-4ce3-11ea-80db-c03ce141bf1a.png)

Because of that, the thumbnails updater can't pull down the correct thumbnails for this game. The thumbs also have different spellings:

![rnrracing2](https://user-images.githubusercontent.com/22120259/74245534-6f7d6f00-4ce3-11ea-8c6e-5e17e3a187db.png)

Looks like this will require a bit of renaming of database entries and/or thumbnail filenames.

**Comment by 3XistencE** [comment]
I confirm the problem, i can't see any thumbnail too for Rock n'Roll racing

**Comment by RobLoach** [comment]
Looking to outright delete the deprecated files entirely in https://github.com/libretro/libretro-database/issues/822

We'd lose some metadata (genre, release dates, etc), but the titles would get fixed.

**Comment by RobLoach** [comment]
I think these are different entries. You can see them in:
https://datomatic.no-intro.org/?page=search

**Comment by RobLoach** [comment]
Rock & Roll Racing (Europe) (Beta)
--
2009-10-01 | Trusted Dump
 
Rock 'N' Roll Racing (Europe)SNSP-RN-NOE, SNSP-RN-SCN, SNSP-RN-UKV; SHVC-1A0N-20, SHVC-1A0N-10
1994-04-18 | Rock_n_Roll_Racer_EUR_SNES-GCS
2011-01-02 | Trusted Dump
2013-03-24 | Trusted Dump
2018-11-06 | Trusted Dump
 
Rock N' Roll Racing (Japan)SHVC-RN
2014-08-15 | Trusted Dump
2008-02-20 | Trusted Dump
 
Rock N' Roll Racing (USA)SNS-RN-USA; SHVC-1A0N-10
1993-09-22 | Rock_&_Roll_Racng_USA_FINAL_SNES-REDEMPTION
2013-01-15 | Trusted Dump
 
Rock N' Roll Racing (USA) (Beta)
1993-06-20 | Rock_&_Roll_Racing_JAP_SNES-PARADOX
2018-11-15 | Trusted Modification
