### ISSUE TITLE
Add dat or text file in thumbnail repository

### ISSUE THREAD

**Issue by zach-morris** [libretro-thumbnails/libretro-thumbnails#72]
Without cloning the entire repository for a particular thumbnails repo, it's difficult to know what files are present because github truncates the results at 1000.

This request is to add a commonly named dat or text file, which simply contains the listing of files present in the repository.  This one file would be much more efficient and would allow tools and scripts to download the file list and then work from that, rather than cloning the entire directory.

**Comment by RobLoach** [comment]
Totally agree... There's [libretro-thumbnails-check](https://github.com/RobLoach/libretro-thumbnails-check) that'll build a table of games and whether boxart/titles/snaps are there.

Having a DAT or a tree list directly in the repo would be great.
