### ISSUE TITLE
Cloudflare CNAME issues - Error 1014 CNAME Cross-User Banned

### ISSUE THREAD

**Issue by ner00** [libretro-thumbnails/libretro-thumbnails#74]
This isn't an issue with the repository itself, but I thought that I should report it here in case it wasn't brought to your attention yet. CNAMEs for both https://thumbnails.libretro.com/
and https://thumbnailpacks.libretro.com/ are failing with the error in the title. 

This does not seem to be affecting all connections in the same way, I sometimes can access thumbnails briefly when using a web proxy or Tor, but that ceases to work after a few minutes; when testing with Tor, I have to cycle through a few different nodes before I get one that works (briefly).

**Comment by ner00** [comment]
@RobLoach ^

**Comment by RobLoach** [comment]
Thanks for the report! Will consult with the rest of the team.

**Comment by ner00** [comment]
While the secure access (https) does not work (yet?), the unencrypted access (http) is now working, which is the only of importance since it is the one used for scraping by RA:
http://thumbnails.libretro.com/
http://thumbnailpacks.libretro.com/

**Comment by ner00** [comment]
https is now working too.
