### ISSUE TITLE
Replacing Boxart with More Accurate/Correct region art.

### ISSUE THREAD

**Issue by ToukoKino** [libretro-thumbnails/libretro-thumbnails#78]
I understand this is something that's sort of minor but I notice some boxarts like for the Rockman World series (the GB Mega Man games) the Boxart is the US art as opposed to the Japanese art, is there a reason for that or was it just tossed in there as that so it wouldn't be blank?

In addition a major issue that I noticed is that Genesis games with the red-stripe tend to have this incorrect bolded font that looks fake and fan-made compared to the original font (To the point where even Limited Run Games used the fake font for their SoR4 Limited Editions), which somebody has taken the time to go through and fix the boxart for all of these games for use on a Genesis Mini https://drive.google.com/drive/folders/1l-NOXpyI9PFSDWyIg2V8qP5CqsAmHxQk

I don't know if this is a really important thing or not but I imagine for the sake of accuracy it would be nicer to have the correct box art instead of having to dig around to get one that is accurate from somewhere like Gamefaqs where it might also be in poor quality.

**Comment by masanasake** [comment]
It's been years, but if you're still out there, I took what I could from this, which was about half of it. Things would probably have been different and easier if higher that 512 width was accepted. Read through my PR for more details. Thanks for this submission.

**Comment by masanasake** [comment]
@ToukoKino The PR was merged; would you mind closing this issue? Thanks

**Comment by ToukoKino** [comment]
Done
