### ISSUE TITLE
Some thumbnail names not detected, possibly due to database changes?

### ISSUE THREAD

**Issue by Banjo-Oz** [libretro-thumbnails/libretro-thumbnails#79]
I haven't used RA in awhile and added a bunch of Atari 2600 games and downloaded thumbs for them today. I noticed some didn't get assigned thumbs even though they are there if I download from this git and copy them manually. The reason seems to be that while RA matches the "wrong" romname it doesn't do the same for thumbnails. 

Example: "Acid Drop (USA)" is detected and added to a A2600 playlist, where it is listed as "Acid Drop (Europe)". However, it is not given a thumbnail and downloading doesn't give it one. In this git, the thumbnail is named "Acid Drop (USA).png" like the rom, but since the database wants to change this to "Acid Drop (Europe)", the only way to get a thumbnail to show up is for me to manually rename the thumb to "Acid Drop (Europe).png".

Does this mean that some thumbs in this git are currently wrongly named and should in fact be renamed to match the RA database expectations rather than the rom names.

Another example is "Action Force (USA)" being detected as "Action Man - Action Force (Europe)" which is fine and AKAIK correct... but the thumbnail is still named "Action Force (USA).png" and thus does not display in RA.

I've been manually renaming the thumbs on my PC but should the ones on this git be renamed or is the issue with my RA configuration instead?

**Comment by RobLoach** [comment]
Quite possibly some are missing or renamed. They're over  at:
https://github.com/libretro-thumbnails/Atari_-_2600

To update them, you can use the github application to send updates.

**Comment by Rstation4** [comment]
This issue has happend to me as well. Is the option enabled so we can contribute missing thumbnails as well. I have put a request for PSP PSN/ PSP Mini's/ and PSP PS1 Eboots as well which I would like to contribute to. PSP Eboots can actually be renamed as well so when added via manual scan I can place my thumbnails for them. IE Eboot.pbp --> Rapid Reload.pbp

**Comment by eddlang** [comment]
> 
> 
> To update them, you can use the github application to send updates.

How can we tell which name is correct, the one in the ROM DB or the one in thumbnail DB? For example, Rambo III is named as the following:

ROM DB: **Rambo III (USA, Europe, Korea) (Rev A)**
Thumbnail DB: **Rambo III (World) (Rev A)**

**Comment by RobLoach** [comment]
The ROM DB is always the right one. Likely that the thumbnail needs a rename.

**Comment by masanasake** [comment]
@Banjo-Oz if this issue is resolved, would you mind closing the issue? Thanks
