### ISSUE TITLE
Windows naming problems

### ISSUE THREAD

**Issue by alfrix** [libretro-thumbnails/libretro-thumbnails#8]
### No quotes allowed:

FBA
Named_Boxarts/Crouching Tiger Hidden Dragon 2003 (set 1) [Bootleg, Hack of "The King of Fighters 2001"].png

### 2 files different case (windows is case insensitive):

3DO
Named_Boxarts/Off-World Interceptor (USA).png
Named_Boxarts/Off-world Interceptor (USA).png
Named_Boxarts/Putt-Putt Goes to the Moon (USA).png
Named_Boxarts/Putt-putt goes to the moon (USA).png
Named_Boxarts/Starblade (USA).png
Named_Boxarts/StarBlade (USA).png
Named_Boxarts/Trip'd (USA).png
Named_Boxarts/Trip'D (USA).png

### No Colons allowed:

TurboGrafx CD
Named_Snaps/ImageFight II: Operation Deepstriker (Japan).png
Named_Titles/ImageFight II: Operation Deepstriker (Japan).png

Saturn
Named_Boxarts/Cyberbots: Fullmetal Madness (JAP).png
Named_Boxarts/Dragon Force II: Kamisarishi Daichi Ni (Japan).png

**Comment by RobLoach** [comment]
Good find. The following characters are replaced:
```
&*/:`<>?\|
```
 We should likely add `"` to the list, and update it in RetroArch.

**Comment by alfrix** [comment]
The ` is actually allowed on windows

> I had a script to replace them before, not sure where it went.

replaced with what?

**Comment by RobLoach** [comment]
Replace the characters with `_` across all filenames.

**Comment by alfrix** [comment]
Done.
