### ISSUE TITLE
NES Classic Accurate Covers

### ISSUE THREAD

**Issue by RobLoach** [libretro-thumbnails/libretro-thumbnails#80]
https://www.reddit.com/r/emulation/comments/hw0nvd/nes_classic_accurate_usa_cover_art_250_covers_wip/

cc @kwyxz 

- [x] Super Nintendo USA 
- [ ] Sega Genesis USA 
- [ ] Sega 32X USA 
- [ ] TurboGrafx-16
- [ ] NES

**Comment by kwyxz** [comment]
They gave us their blessing https://www.reddit.com/r/emulation/comments/hw0nvd/nes_classic_accurate_usa_cover_art_250_covers_wip/fz4ovju/

**Comment by masanasake** [comment]
@RobLoach is there more that needs to be done here, or could you close this issue?

**Comment by RobLoach** [comment]
I forget what this is about
