### ISSUE TITLE
Sega Dreamcast - Soulcalibur (USA) thumbnail naming

### ISSUE THREAD

**Issue by Piccadilly** [libretro-thumbnails/libretro-thumbnails#81]
"Soul Calibur (USA)" should be renamed to the correct "Soulcalibur (USA)" as one word as per Redump DB

**Comment by RobLoach** [comment]
Thanks! Fixed at https://github.com/libretro-thumbnails/Sega_-_Dreamcast/commit/a54b7eb779e4ff4547f414bd85775ac033cfc01a
