### ISSUE TITLE
[Nintendo 64] add Thumbnail for Cruis'n World (Europe) (Rev 1)

### ISSUE THREAD

**Issue by NextBlaubeere** [libretro-thumbnails/libretro-thumbnails#84]
Hi,

I noticed that there is a valid rom of "Cruis'n World (Europe) **(Rev 1)**", which does not have a thumbnail.
This should be an easy fix, because there are some for "Cruis'n World (Europe)".

best regards

**Comment by RobLoach** [comment]
Feel free to fix it through a Pull Request :wink:
