### ISSUE TITLE
LucasArts / ScummVM Thumbnails have stopped working due to renamed PNGs

### ISSUE THREAD

**Issue by mrmatteastwood** [libretro-thumbnails/libretro-thumbnails#87]
Hey guys! I noticed that a number of ScummVM games no longer have thumbnails. When I deleted my ScummVM playlist and re-imported my entire ScummVM games folder, I got the following result:

![image](https://user-images.githubusercontent.com/22120259/100719834-70d86f00-33bd-11eb-8b53-bce1da1b56e3.png)

None of these games have working thumbnails, except Loom (FM-Towns). However, looking at http://thumbnails.libretro.com/ScummVM/Named_Boxarts/, it seems like most or all of these thumbnails are there, just with different file names. It seems like the database entries and thumbnail filenames no longer match for a good chunk of ScummVM-compatible games.

Also, I noticed that several games, like The Dig or Flight of the Amazon Queen, didn't get imported at all.

Is there any way I can help with this? I'll be happy to rename db entries and thumbnail filenames for any games I have in my collection. I'd just need a quick pointer on how to do that, since I have very little experience with this.

**Comment by RobLoach** [comment]
Updated this quite a bit. Removed all brackets from the entries.
