### ISSUE TITLE
Wrong image for F1 Racing Championship (Brazil) (En,Fr) boxart (I attached the correct image for the boxart)

### ISSUE THREAD

**Issue by Shideravan** [libretro-thumbnails/libretro-thumbnails#88]
That's the correct image.
![F1 Racing Championship (Brazil) (En,Fr)](https://user-images.githubusercontent.com/12163923/105787215-4b02bd00-5f5d-11eb-96f6-ba0561a0df89.png)

**Comment by masanasake** [comment]
@Shideravan It looks like this was added in https://github.com/libretro-thumbnails/Nintendo_-_Nintendo_64/pull/52 Would you mind closing the issue? Thanks
