### ISSUE TITLE
[Request] Boxarts for Sega Model 1,2,3, and Naomi

### ISSUE THREAD

**Issue by Rstation4** [libretro-thumbnails/libretro-thumbnails#92]
Requesting boxarts thumbnails for Sega Naomi, Sega Model 1,2,3

edit: Sorry I ment to post this in the Libretro-thumbnails section. Someone can move it for me I dont know how to do so.

**Comment by RobLoach** [comment]
Thanks! https://github.com/libretro-thumbnails/libretro-thumbnails/issues/91
