### ISSUE TITLE
[Request] Adding PC-98 thumbnails to the database

### ISSUE THREAD

**Issue by Rstation4** [libretro-thumbnails/libretro-thumbnails#93]
As for PC-98 there is no database for roms or even on the monochrome xmb theme a icon for it. If I can submit my own as a start where do I go. I only have Boxarts and Snaps for Touhou pc-98 games so far.

**Comment by RobLoach** [comment]
Sweeeet! Added https://github.com/libretro-thumbnails/NEC_-_PC-98
