### ISSUE TITLE
Thumbnails for atomiswave games 

### ISSUE THREAD

**Issue by Gun-Striker** [libretro-thumbnails/libretro-thumbnails#94]
there is no atomiswave/naomi games thumbnails, please add those

**Comment by Rstation4** [comment]
I second this, I want be able to contribute the thumbnails that I have already. Not just for this system/core either.

**Comment by Rstation4** [comment]
I created a fork and added Atomiswave along with Sega Naomi.

**Comment by masanasake** [comment]
This is in the works with PR https://github.com/libretro-thumbnails/libretro-thumbnails/pull/97. Would you mind closing the issue @Gun-Striker or @RobLoach ?
