### ISSUE TITLE
Which rom naming convension is used?

### ISSUE THREAD

**Issue by LordPinkerton** [libretro-thumbnails/libretro-thumbnails#95]
I noticed quite a few roms are not being given thumbnails in my romsets due to the naming convention being slightly different. Example is GBA _"Bomber Man Jetters - Game Collection (Japan)_" in the thumbnail database, but the No-Intro entry is "_Bomberman Jetters - Game Collection (Japan)_" or Atari 2600 "_Acid Drop (USA)_" but the No-Intro entry being "_Acid Drop (Europe)_".

So my question or issue is, what database set are the thumbnails based off of? Redump, No-Intro, something else? What database can I run my roms through to ensure that if I have the rom and it has a thumbnail, that it will match by naming convention instead of me having to go through literally thousands of roms to match them with the thumbnail database so they match correctly?

**Comment by RobLoach** [comment]
No-Intro often updates it's names, so that one could likely do with a rename.

**Comment by LordPinkerton** [comment]
> I hope most of this is covered over at https://github.com/libretro/libretro-database .

These link over to dat o matic website which are the dats I am currently using. Unless the thumbnail database is using some older version dat.
